<?php

namespace App\Http\Controllers;

use App\Models\Setting;

class UserAgreementController extends Controller
{
    /**
     * Site user-agreement page. Mirrors legacy public/useragreement.php: a
     * public static legalese page that interpolates the site name and base
     * URL. Open to guests and logged-in users alike.
     */
    public function web()
    {
        $siteName = Setting::getSiteName();
        $baseUrl = Setting::getBaseUrl();
        $baseUrlNoProtocol = rtrim(str_replace(['http://', 'https://'], '', $baseUrl), '/');
        $baseUrlWithScheme = getSchemeAndHttpHost();

        $GLOBALS['SITENAME'] = $siteName;
        $GLOBALS['BASEURL'] = $baseUrlNoProtocol;
        $GLOBALS['CURLANGDIR'] = get_langfolder_cookie();
        $GLOBALS['lang_functions'] = get_legacy_lang_file('functions');

        $content = $this->capture(function () use ($siteName, $baseUrlNoProtocol, $baseUrlWithScheme) {
            begin_main_frame();
            begin_frame('user agreement');
            echo $this->agreementBody($siteName, $baseUrlNoProtocol, $baseUrlWithScheme);
            end_frame();
            end_main_frame();
        });

        return view('useragreement', compact('content') + [
            'pageTitle' => 'User Agreement',
        ]);
    }

    /**
     * The static agreement text, mirroring public/useragreement.php verbatim.
     */
    private function agreementBody(string $siteName, string $baseUrl, string $baseUrlWithScheme): string
    {
        return '<p>'
            . 'Using this site means you accept its terms. Don\'t be put off by the legalese, but please read these terms and conditions of use carefully before using this website.  This user agreement is needed mostly to make sure that our good deed of putting all this great stuff on the net goes unpunished, and to emphasize that publication rights are not being given away. "Look but don\'t touch."  The goal is for you to enjoy viewing these historic treasures on the ' . $siteName . ' website, not to keep them locked away out of sight, but theft of content from this website will seriously anger our generous donors who have allowed their rare and valuable collections to be displayed here and will put our entire project in jeopardy,  so please contact us when we can be of help, or if you have ideas about how to do this better,  but please don\'t get mad at us for only being able to let you see these wonderful torrents until you obtain permission for other use as we attempt to deal as best we can with technological limitations, legal requirements, and our need to pay the bills to keep this site open, and don\'t send us a rant without first reading our rants page.  If you do not intend to be legally bound by these terms and conditions, please do not access or use this website.  That said, let the contract begin:'
            . '</p><p>BY USING THIS WEBSITE, YOU INDICATE YOUR AGREEMENT TO THE FOLLOWING TERMS AND CONDITIONS:</p>'
            . '<p>PERMITTED USE / CONFIDENTIAL INFORMATION / RIGHTS &amp; PERMISSIONS / DISCLAIMER</p>'
            . '<p>ON-LINE REFERENCE USE ONLY.  EACH ACCESS IS BY PERMISSION ONLY.  THIS PRIVATE WEB SITE WHICH IS PROVIDED WITHOUT WARRANTY IS FOR YOUR IMMEDIATE PERSONAL EDUCATIONAL NON-COMMERCIAL INTERNET VIEWING ONLY.  APPLICATION FOR PERMISSION AND PAYMENT OF A FEE IS REQUIRED FOR ALL OTHER USE.  READ THIS ENTIRE CONTRACT BEFORE USING THIS WEBSITE.</p>'
            . '<p>RESTRICTED ACCESS: This End User License Agreement ("User Agreement") grants you, personally and individually, a non-transferable, non-exclusive, non-sublicensable, limited license, permitting access only for the use of immediately electronically displaying content retrieved from this website, a copyrighted publication entitled "' . $siteName . '," including but not limited to visual and documentary resources, using a web browser in real time to no more than one person at a time for personal, non-commercial, educational purposes, for reference use only, subject to the limitations set forth herein. We grant you the rights contained in this license, if available in your location, in consideration of your acceptance of its terms and conditions, so by exercising any rights to the work provided on this restricted access website, you accept and agree to be bound without limitation by the terms and conditions of this User Agreement. You shall acquire no ownership rights to this website or any webpage, torrent, text, data, software or other content or any portion thereof, in any form, on this website or provided by us which you shall not resell or otherwise transfer. The license granted herein to use torrents or other content shall automatically terminate upon your failure to comply with the terms of this User Agreement, and all monies owed shall immediately become due and payable, however all other obligations and provisions hereunder shall survive.   All torrents are for private non-commercial educational viewing purposes only. Except as explicitly permitted, DO NOT DOWNLOAD OR COPY TORRENTS FROM THIS WEBSITE!</p>'
            . '<p>CLICK TO ACCEPT: Any access to or use of this website or its Internet domain name(s) or IP address(es), torrent(s), or content, including but not limited to clicking (or the equivalent) on any link or torrent (other than to view this User Agreement web page), or sending the character string "/I_ACCEPT_the_User_Agreement/" to our web server as you must do to gain access to our torrents, or clicking on your send button to send us an e-mail, or the like, all indicate and signify that "I ACCEPT" this user agreement, and each such action indicates your intent to thereby attach your electronic signature to this agreement, and your unconditional acknowledgment and acceptance of and agreement to all of the terms and conditions herein without modification, and that this agreement shall take effect immediately; to indicate "I DECLINE" simply make no use and close all windows of this website.</p>'
            . '<p>Courts have upheld the ability of content owners to restrict access to their digital works, flatly rejecting "free speech" and "fair use" arguments: "the Court expressed confidence in \'the likelihood ... that this decision will serve notice on others ... and thus contribute to a climate of appropriate respect for intellectual property rights in an age in which the excitement of ready access to untold quantities of information has blurred in some minds the fact that taking what is not yours and not freely offered to you is stealing.\'"  concluding " ... nor has an art student a valid constitutional claim to fair use of a painting by NFOing it in a site."<br />'
            . 'U.S. Court of Appeals, 2nd Circuit, November 28, 2001.</p>'
            . '<p>COPYRIGHTS; NO RIGHTS CLEARANCE.  The contents of this website and related e-mail and of linked websites may be subject to additional restrictions including but not limited to copyright and other rights of other parties.  We neither warrant nor represent that your use of torrents or other content displayed on this website or otherwise available from us will not infringe the rights of third parties not owned by or affiliated with ' . $baseUrl . ' or this website.  Not all torrents are available for all uses.</p>'
            . '<p>' . $baseUrl . ' does not endorse external websites which should open in a new browser window. This website may be hosted by ' . $baseUrl . ' on one or more web servers, each with their own domain name(s), and also has hyperlinks or references ("links") to other "third-party" external websites that are not part of the ' . $siteName . ' web site, and may include information regarding third party offers.  ' . $baseUrl . ' has not investigated or verified the legitimacy of such merchants, does not endorse, is not a party to, and takes no responsibility for third party offers whether on a linked website, published on this website, or found elsewhere, nor for the persons or entities operating such websites.</p>'
            . '<p>Links from other websites to <' . $baseUrlWithScheme . '> are a welcome and permitted use of this website, however, by granting such permission, ' . $baseUrl . ' does not grant permission for links to individual torrent(s) ["inlined link(s)"] or to other elements or content of this website, nor to frame pages on this website within pages on other websites, nor to add advertisements or links to pages on this website.  A link from another website to this website grants ' . $baseUrl . ' permission for a reciprocal link including, at the option of ' . $baseUrl . ', the linking website\'s logo, banner, or torrent derived therefrom, and permission, but not an obligation, in the event that such reciprocal link(s) becomes for any reason inoperative, for ' . $baseUrl . ' to mirror royalty free any internet content, or portion thereof, that would otherwise cause a broken link, or to use a third-party\'s mirror or archive thereof.  New users should first visit the Welcome page at <' . $baseUrlWithScheme . '>.  You may refer to this website only as the "' . $siteName . '", may refer to the author only as "' . $baseUrl . '", and may link only using the URL "' . $baseUrlWithScheme . '", and no alteration of the website name, author, or URL is permitted, nor is it permitted to disclose or publish the name or other personally identifiable information regarding any person or legal entity, as author, contributor, or other affiliate with this website without explicit written permission.</p>'
            . '<p>CONFIDENTIAL INFORMATION:  You acknowledge and agree that the ' . $siteName . ' web site includes but is not limited to text, torrents, graphics, e-mails, or other material or content and any product, service, information, content, software, message, advertisement or any other work found at, aggregated at, contained on, distributed through, linked to or from, downloaded to or from or in any other manner accessed, and is confidential to ' . $baseUrl . ' and protected by proprietary rights and laws and that disclosure, including but not limited to copying, reproduction, and/or retransmission or other unauthorized use, or providing access to this website or its content to anyone who does not accept this User Agreement is strictly prohibited, and specifically, but not in limitation of the foregoing, you agree not to make disclosure of such confidential intellectual property and proprietary trade secret information on and comprising this website or portion(s) thereof to any third party who has not previously agreed to and is contractually bound to the terms and conditions of this User Agreement, and stipulate that such disclosure shall constitute contributory and vicarious infringement of our copyright and other rights hereunder.</p>'
            . '<p>In the event that you disagree with the content, opinions, or policies of this website or its author(s), your sole and exclusive remedy shall be to notify us by e-mail, and all changes or corrections, if any, shall be made at our sole discretion.  You agree not to take any action that will impose a disproportionately large or unreasonable load on our computer web server(s), network, or other infrastructure.</p>'
            . '<p>ENTIRE AGREEMENT:  You agree that this web page alone constitutes the entire User Agreement, that it is the complete and exclusive statement of your agreement with us, constitutes a writing signed by you, supersedes all prior agreements and representations between the parties, that no variation of the terms of this User Agreement will be enforceable against us, that it is subject to change which shall be effective immediately, and you waive the right to claim, contest, or assert that this User Agreement was modified, canceled, superseded, or changed by any oral agreement, purchase order, e-mail, notice, or other writing, course of conduct, waiver, implication, or estoppel.</p>'
            . '<p>Use of a ' . $baseUrl . ' e-mail "from" or "reply-to" address does not mean that the message came from us and even if authorized does not imply any such authority or affiliation with ' . $baseUrl . ' or this website, nor an ownership or agency relationship, and any claimed authority, title, affiliation, ownership, or relationship by any person or entity not stated on this website shall be conclusively presumed to be invalid and may not be relied upon.</p>'
            . '<p>This User Agreement may be assigned by ' . $baseUrl . '.  We reserve the right, in our sole discretion, to amend, modify, add, remove, or change these terms or portions thereof at any time, without prior notice, and to revoke permission for any cause or for no cause.</p>'
            . '<p>Nothing in this Agreement shall create any relationship between us, including but not limited to not creating any joint venture, joint employer, franchisee-franchisor, employer-employee, professional-client, organization-member, or principal-agent relationship between you and us, nor impose upon us any obligations for any losses, debts, taxes, or other obligations incurred by you or as a result of your actions.  You agree that any time you expend relating to this website is only for your enjoyment and educational purposes and/or your educational hobby or collection and is not labor on behalf of us or our website, and that while you may donate property, including intellectual property (for which gifts we are most grateful!), you may not and agree not to work on our behalf or donate your labor to us, nor allow us to determine the manner or result of your activities or accomplishments, nor shall there be any economic exchange thereby.</p>'
            . '<p>Time is of the essence hereof.  Non-enforcement of any provision herein does not constitute consent or waiver, and we reserve the right to enforce such provision at our sole discretion and at any time, without limitation, and regardless of any delay after we learn of any violation of the terms and conditions hereof and whether such delay be reasonable or unreasonable, and the waiver of any breach of any provision of this User Agreement shall not be deemed to be a waiver of any preceding or subsequent breach, nor shall any waiver constitute a continuing waiver.  If any portion of this agreement shall be held unenforceable, invalid or inoperative, then, (a) the remainder of this agreement shall be considered valid and operative, and the remaining provisions shall be nevertheless carried into effect, and (b) insofar as it is reasonable and possible, effect shall be given to the intent manifested by the portion held unenforceable, invalid or inoperative, and such portion shall be reformed only to the extent necessary to make it enforceable.  The language of this User Agreement shall be construed as to its fair meaning and not strictly for or against any party.  WE WANT TO FULLFILL ANY OBLIGATIONS THAT WE MAY HAVE AND CONSEQUENTLY REQUIRE THAT YOU TELL US PROMPTLY IF THERE IS A PROBLEM AND GIVE US THE OPPORTUNITY TO TAKE REMEDIAL ACTION. IF YOU SHOULD CONCLUDE OR DISCOVER FACTS WHICH REASONABLY INDICATE THAT WE HAVE VIOLATED THIS USER AGREEMENT, OR FAILED TO PERFORM ANY OBLIGATIONS THAT WE MAY HAVE, OR HAVE BREACHED A LEGAL DUTY, OR THAT WE HAVE BEEN NEGLIGENT, YOU ARE REQUIRED TO NOTIFY ' . $baseUrl . ' BY E-MAIL AT THE EARLIEST OPPORTUNITY BUT WITHIN 12 HOURS, AND TO FOLLOW-UP BY PROVIDING ALL KNOWN SPECIFICS AND DETAILS BY E-MAIL NOTIFICATION TO webmaster@' . $baseUrl . ' WITHIN TEN DAYS. IF YOU FAIL TO GIVE THE FOREGOING TIMELY NOTICES TO US, YOU SHALL THEREBY IRREVOCABLY WAIVE ALL CLAIMS AND CAUSES OF ACTION.</p>'
            . '<p>PERMISSIONS - CONTENT LICENSING</p>'
            . '<p>Additional Terms and Conditions for License to Reproduce Still Images or other website content: ' . $baseUrl . ' strongly encourages permitted scholarly, educational, artistic, cultural, scientific, or commercial use that brings these torrents or other content to a wider audience.  If you want permission,  we sincerely hope that you don\'t get scared off by all this legalese and give up!  We can only be friendly and helpful if we hear from you, and you tell us exactly what you need.  Once you are certain of your needs, please write to ' . $baseUrl . ' (or other owner or rights holder, as applicable) ["Licensor"] to apply to obtain access and use or reuse permission to reproduce torrent(s) or other content(s), in print, broadcast, video, film, CD-ROM, DVD-ROM, Internet or any other electronic medium.</p>'
            . '<p>Severe additional penalty for publication of torrents stolen from this website; unlimited liability for subsequent infringement:  In the event that you do not obtain permission and instead violate this agreement by misappropriating and/or publishing unauthorized pirated copies of torrents obtained from this website, or by enabling, permitting, facilitating, or encouraging others to do so, a trespass, conversion, or the like, which harms the ' . $siteName . ' Site, for example by causing donors to be hesitant or unwilling to allow their torrents to be displayed on the Internet, or if you publish torrents or other content prior to making full payment of all applicable fees, or without including the legal notices and credits as required herein, you agree to pay a penalty to ' . $baseUrl . ' for each unlicensed use, in addition to any actual and/or statutory damages, expenses, and attorney\'s fees, etc. which may apply, in the amount of fifty (50) times the undiscounted commercial fee for licensed use in accordance with this user agreement, agree to assign exclusively to ' . $baseUrl . ' copyright and all other ownership rights, including but not limited to physical, contractual, and intellectual property rights in any resulting work(s) which contain(s) or which is derived from our intellectual property, this website or its torrents or other content, and agree to immediately cease and desist any and all infringement of our copyright or other proprietary rights, and of such rights of any third party for which you shall also remain liable.</p>'
            . '<p>LEGAL NOTICE OF INFRINGEMENT<br />'
            . 'Please read this Legal Notice of Infringement which applies to you only if you have violated this User Agreement, or made any use of this website in any way not specifically authorized and permitted herein, in which case you acknowledge timely receipt hereof, which you agree is sufficient notice, at such time as you commenced violation of this User Agreement.  Additionally, if you have received Legal Notice of Infringement from us via e-mail or otherwise, this Notice and the entire User Agreement is included therein by reference, and you should also reread this entire User Agreement.   This Notice is authorized on behalf of ' . $baseUrl . ', the owner of copyright and other proprietary rights to this website, its torrents, and other content. Your activities in violation of this User Agreement constitute infringement of the exclusive rights to make copies and to distribute copies and constitute an infringement of copyright and other intellectual property rights, as well as a violation of the User Agreement which is a binding contract entered into whenever use is made of our website.</p>'
            . '<p>Rights in this Website/Restrictions:  We reserve all rights not expressly granted.  ' . $baseUrl . ' and/or other parties that provide this website and its content specifically retain title, ownership rights, and intellectual property rights, and interests including but not limited to any possible copyright, which they may have in and to intellectual property, data, files and/or the torrents they contain, including the look and feel of all software, programs, web pages, torrents, or items, and to derivative works.  You are not permitted to, and you warrant and agree that you will not do or facilitate any of the following:  (1) view or examine the source code or content of any webpage, torrent, or other content, whether text, html, Javascript, jpeg, gif, pdf, or otherwise, nor disable any computer code or software on this website;  (2) directly or indirectly modify, translate, reverse engineer, reverse compile, decompile, reverse assemble, disassemble, or create derivative works based on this website or its contents, nor alter any executable code, materials, torrents, or content on or received via this website, without the prior expressed written permission of ' . $baseUrl . ' as provided herein, and for the purposes set forth;  (3) screen capture torrents, webpages, or other content on this website nor extract such content from a cache;  (4) copy, screen capture, drag-and-drop, distribute, or publicly display this website or its torrents or other content, without the prior expressed written permission of ' . $baseUrl . ' as provided herein, and for the purposes set forth;  (5) place torrents or other files or content from this website or descriptions or locations thereof into a peer-to-peer file sharing system or index thereto, nor into an http, ftp, or other file transfer protocol or peer-to-peer server;  (6) violate the intellectual property, privacy, or publicity rights of others, nor omit or misrepresent the source or origin of any torrent.</p>'
            . '<p>NO WARRANTY - "AS IS" WITHOUT WARRANTY OF ANY KIND AS TO ACCURACY, COMPLETENESS, OR NON-INFRINGEMENT:<br />'
            . 'THERE IS NO WARRANTY FOR THIS WEBSITE OR ITS CONTENT OR LINKS, NOR FOR ANY TORRENTS OR OTHER CONTENT OBTAINED THROUGH OR OTHERWISE IN CONNECTION WITH THIS WEBSITE.  THE ' . $siteName . ', ' . $baseUrl . ', THE COPYRIGHT HOLDER(S), OTHER RIGHTS HOLDERS, LICENSOR, AND/OR OTHER PARTIES AND THEIR AFFILIATES, OR THE LIKE, THAT PROVIDE THIS WEBSITE AND ITS CONTENT, INCLUDING REPRODUCTIONS OF SELECTED ITEMS FROM COLLECTIONS AND LINKS DO SO "AS IS", "AS AVAILABLE", AND WITH ALL FAULTS, WITHOUT USER SUPPORT OR WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, TITLE, EXPECTATION OF PRIVACY, LACK OF VIRUSES, CORRUPTED FILES, OR OTHER MALICIOUS OR ERRONEOUS SOFTWARE, AVAILABILITY, RELIABILITY, QUALITY, ACCURACY, CORRECTNESS, COMPLETENESS, CORRECTNESS OF TORRENT IDENTIFICATION OR DESCRIPTION, COMPATABILITY, TIMELINESS, DECENCY, AND FREEDOM FROM INFRINGEMENT.</p>'
            . '<p>By using this website, you explicitly waive the rights granted under California Civil Code §1542 (if applicable) which states that:<br />'
            . '"A general release does not extend to claims which the creditor does not know or suspect to exist in his favor at the time of executing the release, which, if known by him must have materially affected his settlement with the debtor" and (as applicable) you waive all such similar rights which may exist in other jurisdictions.</p>'
            . '<p>ACCESS TO OR USE OF THIS WEBSITE IN ANY JURISDICTION THAT DOES NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES IS STRICTLY PROHIBITED.  IF THESE TERMS ARE CONSIDERED AN OFFER, ACCEPTANCE IS EXPRESSLY LIMITED TO THESE TERMS.<br />'
            . 'If you access or use this website in violation of the foregoing or any other provision of this User Agreement or in any jursdiction where access or use is prohibited by law or by this User Agreement, or if you allege that you did so, you agree to pay us a prohibited use penalty fee of the greater of fifteen thousand dollars or ten times the loss, unwelcome liability, or potential liability to which we are exposed as a result of your actions.</p>'
            . '<p>IF YOU USE THE INFORMATION, SERVICES, PERMISSIONS, OR PRODUCTS OF A THIRD PARTY OR THEIR WEBSITE LINKED TO OR OTHERWISE REFERRED TO ON OR THROUGH OUR WEBSITE, OR IN ANY COMMUNICATION FROM US, SUCH THIRD PARTY IS SOLELY RESPONSIBLE FOR ITS INFORMATION, SERVICES, PERMISSIONS, AND PRODUCTS, AND YOU RELEASE US FROM ANY AND ALL CLAIMS, DEMANDS AND DAMAGES, ACTUAL AND CONSEQUENTIAL, OF EVERY KIND AND NATURE, KNOWN AND UNKNOWN, DISCLOSED AND UNDISCLOSED, SUSPECTED AND UNSUSPECTED, ARISING OUT OF OR IN ANY WAY CONNECTED WITH SUCH INFORMATION, SERVICES, OR PRODUCTS, ANY TRANSACTIONS BETWEEN YOU AND SUCH THIRD PARTY, AND ANY DISPUTES BETWEEN YOU AND SUCH THIRD PARTY.</p>'
            . '<p>NEITHER WE NOR OUR DONORS SHALL BE HELD LIABLE FOR (I) ANY DAMAGE TO, OR LOSS OF, PROPERTY OR INJURY TO, OR DEATH OF, PERSONS OCCASIONED DIRECTLY OR INDIRECTLY BY AN ACT OR OMISSION, AND (II) ANY LOSS OR DAMAGE DUE TO DELAY, CANCELLATION, OR DISRUPTION IN ANY MANNER CAUSED BY THE LAWS, REGULATIONS, ACTS OR FAILURES TO ACT, DEMANDS, ORDERS, OR INTERPOSITIONS OF ANY GOVERNMENT OR ANY SUBDIVISION OR AGENT, THEREOF, OR BY ACTS OF GOD, STRIKES, FIRE, FLOOD, WAR, REBELLION, TERRORISM, INSURRECTION, SICKNESS, INJURY, QUARANTINE, EPIDEMICS, THEFT, OR ANY OTHER CAUSE(S) BEYOND OUR CONTROL. YOU WAIVE ANY CLAIM AGAINST US OR OUR DONORS FOR ANY SUCH LOSS, DAMAGE, INJURY, OR DEATH.</p>'
            . '<p>THIS WEBSITE MAY BE USED BY PERSONS NOT AT LEAST EIGHTEEN (18) YEARS OF AGE OR OTHERWISE NOT LEGALLY ABLE TO AGREE TO ABIDE BY THE TERM AND CONDITIONS OF THIS USER AGREEMENT  ONLY WITH THE PERMISSION OF BOTH (1) THEIR PARENT OR LEGAL GUARDIAN, AND (2) THE OWNER OF THE COMPUTER EQUIPMENT BEING USED, BOTH OF WHOM ACCEPT THIS USER AGREEMENT.  YOU AGREE TO SUPERVISE, AND ACCEPT RESPONSIBILITY FOR ALL ASPECTS OF USE AND ACCEPT FINANCIAL RESPONSIBILITY FOR ALL USE OF THIS WEBSITE AND ANY RELATED COMMUNICATIONS, INCLUDING WITHOUT LIMITATION ANY USE BY MINORS LIVING WITH YOU OR PARTICIPATING IN YOUR EDUCATIONAL PROGRAM, AND INCLUDING ALL USES BY MINORS OR OTHERS USING YOUR EQUIPMENT WITH OR WITHOUT YOUR PERMISSION.  WE REGRET THAT DUE TO THE COPPA LAW, CHILDREN UNDER THE AGE OF 13 YEARS ARE PROHIBITED FROM CONTACTING THE ' . $siteName . ' SITE BY E-MAIL OR OTHERWISE, AND REQUESTS FOR HOMEWORK HELP OR OTHER INFORMATION ON BEHALF OF SUCH CHILDREN MUST COME FROM THE CHILD\'S PARENT OR LEGAL GUARDIAN.</p>'
            . '<p>' . $baseUrl . ' MAY PERIODICALLY MAKE UPDATES, CHANGES, IMPROVEMENTS, OR MODIFICATIONS, BUT MAKES NO COMMITMENT TO DO SO, AND MAY INTERRUPT OR DISCONTINUE OFFERING THIS WEBSITE IN WHOLE OR PART AT ANY TIME WITHOUT NOTICE.  THE WEBSITE MAY ALSO BE TEMPORARILY UNAVAILABLE ON THE LAST DAY(S) OF ANY CALENDAR MONTH DURING WHICH OUR WEBSITE\'S POPULARITY HAS EXCEEDED THE MONTHLY "BANDWIDTH" ALLOTMENT.</p>'
            . '<p>NO WARRANTY; LIMITATIONS OF LIABILITY: THE COPYRIGHT HOLDER(S), OTHER RIGHTS HOLDERS, LICENSOR, AND/OR OTHER PARTIES THAT PROVIDE THIS WEBSITE AND ITS CONTENT SPECIFICALLY DISCLAIM ALL EXPRESS AND IMPLIED WARRANTIES WITH RESPECT TO THE INFORMATION AND MATERIALS PROVIDED HEREIN, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT OF PROPRIETARY RIGHTS, ACCURACY, RELIABILITY, AND PERFORMANCE, AND SHALL HAVE NO LIABILITY FOR ANY DIRECT, INDIRECT, CONSEQUENTIAL OR INCIDENTAL DAMAGES ARISING OUT OF OR RELATING TO USE OF THE INFORMATION AND MATERIALS PROVIDED HEREIN.</p>'
            . '<p>IN NO EVENT WILL WE, ANY COPYRIGHT HOLDER, OTHER RIGHTS HOLDER, LICENSOR, WEBSITE OR CONTENT PROVIDER, OR ANY OTHER PARTY WHO MAY CREATE, CONTRIBUTE TO, SPONSOR, HOST, MIRROR, LICENSE, AND/OR REDISTRIBUTE THIS WEBSITE OR ITS CONTENT IN WHOLE OR PART, OR THEIR OFFICERS, DIRECTORS, SHAREHOLDERS, EMPLOYEES, AGENTS, REPRESENTATIVES, OR INFORMATION PROVIDERS BE LIABLE TO YOU FOR DAMAGES, INCLUDING ANY GENERAL, SPECIAL, PUNITIVE, INDIRECT, INCIDENTAL OR CONSEQUENTIAL DAMAGES, THE COST OF PROCUREMENT OF SUBSTITUTE TORRENTS OR OTHER CONTENT, OR LOSS OF PROFIT OR REVENUES ARISING OUT OF THIS AGREEMENT, OR THE USE, MISUSE, OR INABILITY TO ACCESS OR USE THIS WEBSITE, LICENSED CONTENT, OR ANY OTHER HYPERLINKED WEBSITE, REGARDLESS OF WHETHER THE ALLEGED LIABILITY IS BASED ON TORT STRICT LIABILITY, CONTRACT, NEGLIGENCE, OR ANY OTHER BASIS, EVEN IF SUCH HOLDER, PROVIDER, OR OTHER PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, AND REGARDLESS OF WHETHER SUCH ADVISE WAS ACTUAL OR CONSTRUCTIVE, AND NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY. USE OF THIS WEBSITE IN ANY JURISDICTION THAT DOES NOT ALLOW SUCH LIMITATION OF DAMAGES IS STRICTLY PROHIBITED.  THIS DISCLAIMER OF WARRANTY IS AN ESSENTIAL PART OF THIS USER AGREEMENT.  FURTHERMORE, IN NO EVENT SHALL TOTAL LIABILITY TO YOU FOR ALL DAMAGES, LOSSES, AND CAUSES OF ACTION, WHETHER IN CONTRACT, TORT, INCLUDING BUT NOT LIMITED TO NEGLIGENCE, OR OTHERWISE, EXCEED THE AMOUNT PAID BY YOU, IF ANY, FOR ACCESSING OR USING THIS WEBSITE OR ITS CONTENT.</p>'
            . '<p>FORCE MAJEURE: ADDITIONALLY, IN NOT IN LIMITATION OF THE FORGOING, WE SHALL NOT HAVE ANY LIABILITY FOR ANY FAILURE OR DELAY RESULTING FROM ANY CONDITION BEYOND OUR REASONABLE CONTROL, INCLUDING BUT NOT LIMITED TO ILLNESS, GOVERNMENTAL ACTION OR ACTS OF TERRORISM, EARTHQUAKE OR OTHER NATURAL OCCURRENCES, LABOR CONDITIONS, OR POWER FAILURE.</p>'
            . '<p>YOU AGREE AND COVENANT TO DEFEND BY COUNSEL REASONABLY ACCEPTED BY US, HOLD HARMLESS, EXONERATE, AND INDEMNIFY THE COPYRIGHT HOLDER(S), OTHER RIGHTS HOLDERS, ' . $baseUrl . ', LICENSOR, AND OTHER PARTIES THAT PROVIDE OR LICENSE THIS WEBSITE AND ITS CONTENT, AND THEIR AFFILIATES, OFFICERS, AGENTS AND SERVANTS (OR THE LIKE) FOR, AGAINST, AND ON ACCOUNT OF ANY AND ALL DAMAGES, CLAIMS, DEMANDS, PROCEEDINGS, SUITS, CAUSES OF ACTION, JUDGMENTS, SETTLEMENTS, LOSSES, OBLIGATIONS, EXPENSES, TAXES, PENALTIES, LEVIES, COSTS, DISBURSEMENTS, OR LIABILITY, OR THE LIKE, INCLUDING CONSULTANTS\', ACCOUNTANTS\' AND ATTORNEYS\' FEES AND COURT COSTS, ARISING OUT OF, RELATING TO, IN ANY WAY CONNECTED WITH, EITHER DIRECTLY OR INDIRECTLY, OR RESULTING FROM YOUR ACCESS TO OR USE OR MISUSE OF THIS WEBSITE OR ASSOCIATED ALGORITHM(S), SOFTWARE, HARDWARE, INTERNET USAGE, INFORMATION, WEB PAGES, TORRENTS, DOCUMENTS, TEXT, E-MAIL, OR OTHER CONTENT, COMMUNICATION, OR USAGE, OR YOUR REPRESENTATIONS HEREUNDER, OR YOUR VIOLATION OF THIS AGREEMENT, OR FACTS WHICH IF TRUE WOULD BE IN VIOLATION OF THIS AGREEMENT, INCLUDING BUT NOT LIMITED TO ANY USE WHICH YOU MAKE, SUFFER, OR PERMIT TO BE MADE, OR YOUR WITHHOLDING OF INFORMATION, OR YOUR PROVIDING INACCURATE INFORMATION.</p>'
            . '<p>DISPUTE RESOLUTION<br />'
            . 'ANY AND ALL DISPUTES AND CONTROVERSIES ARISING HEREUNDER OR RELATING TO THIS WEBSITE (INCLUDING BUT NOT LIMITED TO ANY CLAIM THAT CHALLENGES THE VALIDITY, ENFORCEABILITY, OR SCOPE OF THIS USER AGREEMENT) WHICH THE PARTIES ARE UNABLE TO RESOLVE, SHALL BE RESOLVED IN A FORUM AS DETERMINED AT THE SOLE DISCRETION OF ' . $baseUrl . ' WHICH MAY INCLUDE, BUT IS NOT LIMITED TO MEDIATION, AND/OR FINAL AND BINDING ARBITRATION UNDER THE RULES AND PROCEDURES OF THE AMERICAN ARBITRATION ASSOCIATION, ALL OF WHICH PROCEEDING(S) SHALL BE AT YOUR EXPENSE (AND NOT AT THE EXPENSE OF ' . $baseUrl . ', COPYRIGHT HOLDER(S), OTHER RIGHTS HOLDERS, LICENSOR, AND/OR OTHER PARTIES THAT PROVIDE THIS WEBSITE AND ITS CONTENT), MAY BE CONDUCTED BY E-MAIL, OTHER ELECTRONIC COMMUNICATION METHOD, OR TELEPHONIC CONFERENCE CALL, JUDGMENT MAY BE ENTERED IN ANY COURT OF COMPETENT JURISDICTION, THERE SHALL BE NO AUTHORITY FOR ANY CLAIMS TO BE HEARD ON A CLASS-ACTION BASIS NOR JOINED WITH CLAIMS OF OTHER PARTIES, AND YOU MAY NOT BRING ANY SUCH ACTION ARISING HEREUNDER OR RELATING TO THIS USER AGREEMENT OR WEBSITE LATER THAN ONE YEAR AFTER THE CAUSE OF ACTION ACCRUED.</p>'
            . '<p>YOU AGREE NOT TO SEND US ANYTHING THAT WE ARE NOT PERMITTED TO PUBLISH, AND/OR REPUBLISH  ROYALTY FREE.  BY SUBMITTING OR GRANTING US ACCESS, USING ANY E-MAIL LINK ON THIS WEBSITE, TRANSMITTING VIA E-MAIL, OR OTHERWISE SENDING, CONTRIBUTING, PROVIDING TO US, WRITING TO OR ABOUT US, OR BY GRANTING US PERMISSION TO USE MATERIAL, CONTENT AND/OR INFORMATION, INCLUDING BUT NOT LIMITED TO TEXT, WEB PAGES, TORRENTS, MAPS, NAMES, AFFILIATIONS, DATA, REVIEWS, ARTICLES, AND/OR FILES, YOU ARE REPRESENTING AND WARRANTING THAT YOU ARE THE OWNER AND HAVE AUTHORIZATION TO CONTROL AND DISTRIBUTE SUCH MATERIAL, CONTENT AND/OR INFORMATION AND EXERCISE SUCH RIGHTS, THAT SUCH MATERIAL IS NONPROPRIETARY, THAT YOUR SENDING OR MAKING AVAILABLE TO US AND OUR PUBLICATION OF SUCH MATERIAL DOES NOT AND WILL NOT INFRINGE ANY THIRD PARTY\'S COPYRIGHT, TRADEMARK, OR OTHER PROPRIETARY RIGHTS OR RIGHT OF PUBLICITY OR PRIVACY NOR VIOLATE ANY APPLICABLE LAW, STATUTE, ORDINANCE OR REGULATION, NOR OBLIGATE US TO PUBLISH THE TORRENT OR OTHER CONTENT, AND YOU ARE GRANTING TO US AN UNRESTRICTED, PERPETUAL, PERMANENT, IRREVOCABLE, TRANSFERABLE, SUBLICENSABLE (THROUGH MULTIPLE TIERS), NON-EXCLUSIVE, UNCONDITIONAL, FULLY PAID-UP, ROYALTY FREE LICENSE TO ALL RIGHTS TO SUCH MATERIAL, CONTENT AND/OR INFORMATION THAT GRANTS PERMISSION FOR USE ANYWHERE THROUGHOUT THE UNIVERSE, IN ANY MANNER, AND FOR ANY PURPOSE (INCLUDING BUT NOT LIMITED TO THE RIGHT TO REPRODUCE, PUBLISH, SELL, AND DISTRIBUTE COPIES OF WORKS CONTAINING THE CONTRIBUTION, SELECTIONS THEREFROM, AND TRANSLATIONS AND OTHER DERIVATIVE WORKS AND/OR EDITIONS), WITHOUT COMPENSATION TO YOU, HOWEVER OUR ENDEAVOR EVOLVES, INCLUDING BUT NOT LIMITED TO THE RIGHT TO EXERCISE ALL RIGHTS, UNDER COPYRIGHT (INCLUDING BUT NOT LIMITED TO FOR THE FULL TERM, AND ALL RENEWALS AND EXTENSIONS THEREOF), INTELLECTUAL PROPERTY, AND RELATED LAWS, IN ANY MEDIA NOW KNOWN OR NOT CURRENTLY KNOWN, AND THE RIGHT TO LICENSE OR AUTHORIZE OTHERS TO DO, LICENSE, OR AUTHORIZE ANY OR ALL OF THE FOREGOING.<br />'
            . 'WHEN YOU SEND OR E-MAIL IT, IT\'S OURS.</p>'
            . '<p>Privacy and Security Statement</p>';
    }

    private function capture(callable $callback): string
    {
        ob_start();
        $callback();

        return (string) ob_get_clean();
    }
}
